// <auto-generated />
namespace CrmBL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class update110222 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update110222));
        
        string IMigrationMetadata.Id
        {
            get { return "202202111022258_update110222"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
